### ISSUE TITLE
Não baixa 

### ISSUE THREAD

**Issue by WellingtonMonteiro** [yarrm80s/orpheusdl-qobuz#1]
Logging into Qobuz
=== Downloading album Laundry Service (0074646390023) ===
Artist: Shakira (106694)
Number of tracks: 13
Service: Qobuz

Track 1/13
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/orpheusdl/orpheus.py", line 200, in <module>
    main()
  File "/data/data/com.termux/files/home/orpheusdl/orpheus.py", line 195, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "/data/data/com.termux/files/home/orpheusdl/orpheus/core.py", line 381, in orpheus_core_download
    downloader.download_album(media_id)
  File "/data/data/com.termux/files/home/orpheusdl/orpheus/music_downloader.py", line 139, in download_album
    self.download_track(track_id, album_location=path, track_index=index, number_of_tracks=number_of_tracks, main_artist=artist_name, indent_level=indent_level+1)
  File "/data/data/com.termux/files/home/orpheusdl/orpheus/music_downloader.py", line 172, in download_track
    track_info: TrackInfo = self.service.get_track_info(track_id)
  File "/data/data/com.termux/files/home/orpheusdl/modules/qobuz/interface.py", line 42, in get_track_info
    file_data = self.session.get_file_url(track_id, quality_parse[self.module_controller.orpheus_options.quality_tier])
  File "/data/data/com.termux/files/home/orpheusdl/modules/qobuz/qobuz_api.py", line 105, in get_file_url
    return self._get('track/getFileUrl', params)
  File "/data/data/com.termux/files/home/orpheusdl/modules/qobuz/qobuz_api.py", line 34, in _get
    raise self.exception(r.text)
orpheus.core.ModuleError: qobuz --> {"status":"error","code":400,"message":"Invalid Request Signature parameter (21cca944f7993d07d2b84006429255a4)"}
$

**Comment by yarrm80s** [comment]
You need to add these in the settings.json:

app_id: 640631854
app_secret: 7b500f6fdde47775c62ed3437a94ebc0
