### ISSUE TITLE
Can't download albums

### ISSUE THREAD

**Issue by okay-bullo** [yarrm80s/orpheusdl-qobuz#27]
`=== Downloading album DAMN. COLLECTORS EDITION. (0060256726119) ===
        Artist: Kendrick Lamar (617741)
        Year: 2017
        Duration: 54m:55s
        Number of tracks: 14
        Service: Qobuz
        Downloading booklet
        Downloading album cover

        Track 1/14
Traceback (most recent call last):
  File "C:\Users\EEE\documents\orpheusdl\orpheus.py", line 224, in <module>
    main()
  File "C:\Users\EEE\documents\orpheusdl\orpheus.py", line 219, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "C:\Users\EEE\documents\orpheusdl\orpheus\core.py", line 397, in orpheus_core_download
    downloader.download_album(media_id, extra_kwargs=media.extra_kwargs)
  File "C:\Users\EEE\documents\orpheusdl\orpheus\music_downloader.py", line 242, in download_album
    self.download_track(track_id, album_location=album_path, track_index=index, number_of_tracks=number_of_tracks, main_artist=artist_name, cover_temp_location=cover_temp_location, indent_level=indent_level+1, extra_kwargs=album_info.track_extra_kwargs)
  File "C:\Users\EEE\documents\orpheusdl\orpheus\music_downloader.py", line 294, in download_track
    track_info: TrackInfo = self.service.get_track_info(track_id, quality_tier, codec_options, **extra_kwargs)
  File "C:\Users\EEE\documents\orpheusdl\modules\qobuz\interface.py", line 99, in get_track_info
    stream_data = self.session.get_file_url(track_id, quality_tier)
  File "C:\Users\EEE\documents\orpheusdl\modules\qobuz\qobuz_api.py", line 95, in get_file_url
    return self._get('track/getFileUrl', params)
  File "C:\Users\EEE\documents\orpheusdl\modules\qobuz\qobuz_api.py", line 34, in _get
    raise self.exception(r.text)
orpheus.core.Orpheus.load_module.<locals>.ModuleError: qobuz --> {"message":"Invalid Request Signature parameter (request_sig) (Root=1-64702f57-0cfb46623c6d73fb263797b3)","status":"error","code":400}`

`=== Downloading album Late Registration (0060249882401) ===
        Artist: Kanye West (35950)
        Year: 2005
        Duration: 01h:09m:49s
        Number of tracks: 21
        Service: Qobuz
        Downloading album cover

        Track 1/21
Traceback (most recent call last):
  File "C:\Users\EEE\documents\orpheusdl\orpheus.py", line 224, in <module>
    main()
  File "C:\Users\EEE\documents\orpheusdl\orpheus.py", line 219, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "C:\Users\EEE\documents\orpheusdl\orpheus\core.py", line 397, in orpheus_core_download
    downloader.download_album(media_id, extra_kwargs=media.extra_kwargs)
  File "C:\Users\EEE\documents\orpheusdl\orpheus\music_downloader.py", line 242, in download_album
    self.download_track(track_id, album_location=album_path, track_index=index, number_of_tracks=number_of_tracks, main_artist=artist_name, cover_temp_location=cover_temp_location, indent_level=indent_level+1, extra_kwargs=album_info.track_extra_kwargs)
  File "C:\Users\EEE\documents\orpheusdl\orpheus\music_downloader.py", line 294, in download_track
    track_info: TrackInfo = self.service.get_track_info(track_id, quality_tier, codec_options, **extra_kwargs)
  File "C:\Users\EEE\documents\orpheusdl\modules\qobuz\interface.py", line 99, in get_track_info
    stream_data = self.session.get_file_url(track_id, quality_tier)
  File "C:\Users\EEE\documents\orpheusdl\modules\qobuz\qobuz_api.py", line 95, in get_file_url
    return self._get('track/getFileUrl', params)
  File "C:\Users\EEE\documents\orpheusdl\modules\qobuz\qobuz_api.py", line 34, in _get
    raise self.exception(r.text)
orpheus.core.Orpheus.load_module.<locals>.ModuleError: qobuz --> {"code":400,"status":"error","message":"Invalid Request Signature parameter (request_sig) (Root=1-64702fa0-34b7b47612e963163cb82812)"}
PS C:\Users\EEE\documents\orpheusdl>`

**Comment by yarrm80s** [comment]
@okay-bullo your app secret is probably wrong

**Comment by okay-bullo** [comment]
@yarrm80s how do i get my correct app secret
