### ISSUE TITLE
KeyError: 'format_id'

### ISSUE THREAD

**Issue by bunt4021** [yarrm80s/orpheusdl-qobuz#28]
Error when downloading [`https://www.qobuz.com/gb-en/album/xoxo-jeon-somi/u2wmcsz6onp5b`](https://www.qobuz.com/gb-en/album/xoxo-jeon-somi/u2wmcsz6onp5b). Looks like it's a track that you can't buy individually, might be unavailable to stream? I'm unsure. Cheers!

```
=== Downloading album XOXO (u2wmcsz6onp5b) ===
        Artist: JEON SOMI (11514629)
        Year: 2021
        Duration: 24m:20s
        Number of tracks: 8
        Service: Qobuz
        Downloading album cover

        Track 1/8
        === Downloading track DUMB DUMB (136773154) ===
                Artists: JEON SOMI (11514629)
                Release year: 2021
                Duration: 02m:27s
                Codec: FLAC, bitrate: 2304kbps, bit depth: 24bit, sample rate: 48kHz
                Warning: codec_conversions setting is invalid!

                Downloading track file
                100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30.3M/30.3M [00:01<00:00, 22.2MB/s]
                Retrieving credits
                Tagging file
        === Track 136773154 downloaded ===

        Track 2/8
        === Downloading track XOXO (136773155) ===
                Artists: JEON SOMI (11514629)
                Release year: 2021
                Duration: 03m:27s
                Codec: FLAC, bitrate: 2304kbps, bit depth: 24bit, sample rate: 48kHz
                Warning: codec_conversions setting is invalid!

                Downloading track file
                100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43.5M/43.5M [00:01<00:00, 29.5MB/s]
                Retrieving credits
                Tagging file
        === Track 136773155 downloaded ===

        Track 3/8
        === Downloading track Don't Let Me Go (136773156) ===
                Artists: JEON SOMI, Giriboy (11514629)
                Release year: 2021
                Duration: 02m:59s
                Codec: FLAC, bitrate: 2304kbps, bit depth: 24bit, sample rate: 48kHz
                Warning: codec_conversions setting is invalid!

                Downloading track file
                100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 38.0M/38.0M [00:01<00:00, 29.0MB/s]
                Retrieving credits
                Tagging file
        === Track 136773156 downloaded ===

        Track 4/8
        === Downloading track Anymore (136773157) ===
                Artists: JEON SOMI (11514629)
                Release year: 2021
                Duration: 03m:17s
                Codec: FLAC, bitrate: 2304kbps, bit depth: 24bit, sample rate: 48kHz
                Warning: codec_conversions setting is invalid!

                Downloading track file
                100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 41.9M/41.9M [00:01<00:00, 28.2MB/s]
                Retrieving credits
                Tagging file
        === Track 136773157 downloaded ===

        Track 5/8
        === Downloading track Watermelon (136773158) ===
                Artists: JEON SOMI (11514629)
                Release year: 2021
                Duration: 03m:02s
                Codec: FLAC, bitrate: 2304kbps, bit depth: 24bit, sample rate: 48kHz
                Warning: codec_conversions setting is invalid!

                Downloading track file
                100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36.8M/36.8M [00:01<00:00, 28.1MB/s]
                Retrieving credits
                Tagging file
        === Track 136773158 downloaded ===

        Track 6/8
Traceback (most recent call last):
  File "/orpheusdl/orpheus.py", line 224, in <module>
    main()
  File "/orpheusdl/orpheus.py", line 219, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "/orpheusdl/orpheus/core.py", line 399, in orpheus_core_download
    downloader.download_album(media_id, extra_kwargs=media.extra_kwargs)
  File "/orpheusdl/orpheus/music_downloader.py", line 242, in download_album
    self.download_track(track_id, album_location=album_path, track_index=index, number_of_tracks=number_of_tracks, main_artist=artist_name, cover_temp_location=cover_temp_location, indent_level=indent_level+1, extra_kwargs=album_info.track_extra_kwargs)
  File "/orpheusdl/orpheus/music_downloader.py", line 294, in download_track
    track_info: TrackInfo = self.service.get_track_info(track_id, quality_tier, codec_options, **extra_kwargs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/orpheusdl/modules/qobuz/interface.py", line 126, in get_track_info
    codec = CodecEnum.FLAC if stream_data['format_id'] in {6, 7, 27} else CodecEnum.MP3,
                              ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'format_id'
```

**Comment by bunt4021** [comment]
Ah okay, didn't catch that on my first look, thanks.

**Comment by OrfiDev** [comment]
Whoops my bad, merged
